org, repo = (ENV["GITHUB_REPOSITORY"]||"").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"]||"").split("/")

APP_IDENTIFIERS = [
  "com.massivecreationlab.badges",
  "com.massivecreationlab.badges.watchkitapp",
  "com.massivecreationlab.badges.watchkitapp.extension"
]

platform :ios do
  lane :init_ci do
    github_action(
      api_token: ENV["GH_PAT"],
      org: org,
      repo: repo,
      match_org: match_org,
      match_repo: match_repo,
      writable_deploy_key: true,
      verbose: true
    )
  end

  desc "Sync codesigning certificates"
  lane :sync_certificates do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV['APPSTORE_P8']
    )

    match(
      type: "development",
      storage_mode: "git",
      git_url: "git@github.com:#{match_org}/#{match_repo}.git",
      app_identifier: APP_IDENTIFIERS,
      git_branch: "master"
    )

    match(
      type: "appstore",
      storage_mode: "git",
      git_url: "git@github.com:#{match_org}/#{match_repo}.git",
      app_identifier: APP_IDENTIFIERS,
      git_branch: "master"
    )

  end

  lane :set_version do
    run_number = ENV["GITHUB_RUN_NUMBER"]
    UI.user_error!("GITHUB_RUN_NUMBER not set") if run_number.to_s.empty?

    version = "0.0.#{run_number}"

    increment_version_number(
      version_number: version
    )

    increment_build_number(
      build_number: run_number
    )
  end


  desc "Deliver a new Release build to the App Store"
  lane :release do
    set_version
    build
    upload_to_app_store
  end

  desc "Deliver a new Beta build to Apple TestFlight"
  lane :beta do
    set_version
    build
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  lane :build do
    setup_ci
    sync_certificates

    build_app(
        project: "time.xcodeproj",
        scheme: "ios",
        export_method: "app-store"
    )
  end

end